// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/integrations/supabase/types';
import type { Json } from '@/integrations/supabase/types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://fewcmtozntpedrsluawj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZld2NtdG96bnRwZWRyc2x1YXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDQ5MzYsImV4cCI6MjA1NzQ4MDkzNn0.4xh1npp9zRyXgXkBGB9auWw3gxOoajDYS8sAIopB-To";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Make sure we have a valid API key
if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error("Missing Supabase API key! Authentication and database operations will fail.");
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'apikey': SUPABASE_PUBLISHABLE_KEY,
      'Content-Type': 'application/json',
    },
  },
  db: {
    schema: 'public',
  }
});

// Define the types of RPC functions for better type safety
export type RpcFunctionName = 
  | 'add_website_change_history'
  | 'create_website'
  | 'delete_website'
  | 'get_user_websites'
  | 'get_website_by_id'
  | 'get_website_change_history'
  | 'get_website_content'
  | 'save_website_content'
  | 'update_website'
  | 'update_website_status'
  | 'get_user_pro_status'
  | 'enable_pro_access'
  | 'get_user_licenses'        
  | 'create_license'           
  | 'regenerate_server_key'    
  | 'update_license'
  | 'delete_license'
  | 'get_file_access_for_license'  
  | 'update_file_access'
  | 'check_license_by_keys'
  | 'create_public_bucket';

// Define parameter types for each RPC function
export type RpcParams = {
  'add_website_change_history': {
    site_id: string;
    content_snapshot: Json;
    changed_fields: string[];
  };
  'create_website': {
    website_name: string;
    website_url: string;
    website_template: string;
    website_shop_template: string;
    website_status?: string;
  };
  'delete_website': {
    site_id: string;
  };
  'get_user_websites': Record<string, never>;
  'get_website_by_id': {
    site_id: string;
  };
  'get_website_change_history': {
    site_id: string;
  };
  'get_website_content': {
    site_id: string;
  };
  'save_website_content': {
    site_id: string;
    content_data: Json;
  };
  'update_website': {
    site_id: string;
    website_name: string;
    website_url: string;
    website_template: string;
    website_shop_template: string;
    website_status?: string;
  };
  'update_website_status': {
    site_id: string;
    website_status: string;
  };
  'get_user_pro_status': Record<string, never>;
  'enable_pro_access': Record<string, never>;
  'get_user_licenses': Record<string, never>;
  'create_license': {
    p_script_name: string;
    p_script_file?: string | null;
    p_server_ip?: string | null;
  };
  'regenerate_server_key': {
    p_license_id: string;
  };
  'update_license': {
    p_license_id: string;
    p_script_name?: string;
    p_script_file?: string | null;
    p_aktiv?: boolean;
    p_regenerate_server_key?: boolean;
    p_server_ip?: string | null;
    p_has_file_upload?: boolean;
  };
  'delete_license': {
    p_license_id: string;
  };
  'get_file_access_for_license': {
    p_license_id: string;
  };
  'update_file_access': {
    p_license_id: string;
    p_file_path: string;
    p_is_public: boolean;
    p_delete?: boolean;
  };
  'check_license_by_keys': {
    p_license_key: string;
    p_server_key: string;
  };
  'create_public_bucket': {
    bucket_name: string;
  };
};

// Verbesserte callRPC-Funktion mit zusätzlichem Logging und Fehlerbehandlung
export const callRPC = async <F extends RpcFunctionName>(
  functionName: F,
  params: RpcParams[F]
): Promise<{ data: any | null; error: Error | null }> => {
  console.log(`Calling RPC function: ${functionName} with params:`, params);
  
  try {
    // Überprüfen, ob der Benutzer angemeldet ist
    const { data: sessionData } = await supabase.auth.getSession();
    if (!sessionData.session) {
      console.error(`Error in RPC call to ${functionName}: User is not authenticated`);
      return { data: null, error: new Error('User is not authenticated') };
    }

    // Verwende den Session-Token für die Authentifizierung
    const authToken = sessionData.session.access_token;
    
    // Make sure the API key and auth token are included in every request
    const { data, error } = await supabase.rpc(functionName as any, params, {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${authToken}`
      }
    } as any); // Type assertion for TypeScript compatibility

    if (error) {
      console.error(`Error in RPC call to ${functionName}:`, error);
      return { data: null, error };
    }

    console.log(`RPC call to ${functionName} successful:`, data);
    return { data, error: null };
  } catch (error) {
    console.error(`Exception in RPC call to ${functionName}:`, error);
    return { data: null, error: error as Error };
  }
};

// Funktion zur Überprüfung und Erstellung eines Storage-Buckets
export const checkStorageBucket = async (bucketName: string): Promise<boolean> => {
  try {
    console.log(`Überprüfe Storage-Bucket '${bucketName}'...`);
    
    // Zuerst mit RPC-Funktion versuchen
    try {
      const { data: rpcData, error: rpcError } = await callRPC('create_public_bucket', {
        bucket_name: bucketName
      });
      
      if (!rpcError) {
        console.log(`Bucket '${bucketName}' erfolgreich über RPC erstellt/überprüft`);
        return true;
      }
      
      console.warn("RPC-Bucket-Erstellung fehlgeschlagen:", rpcError);
    } catch (e) {
      console.warn("Fehler beim Aufrufen der create_public_bucket RPC:", e);
    }
    
    // Direkter Weg als Fallback
    try {
      const { data, error } = await supabase.storage.listBuckets();
      
      if (error) {
        console.error(`Fehler beim Abrufen der Buckets: ${error.message}`);
        return false;
      }
      
      const bucket = data.find(b => b.id === bucketName);
      
      if (!bucket) {
        console.log(`Bucket '${bucketName}' existiert nicht, wird erstellt...`);
        
        const { error: createError } = await supabase.storage.createBucket(bucketName, {
          public: true,
          fileSizeLimit: 52428800,
          allowedMimeTypes: null
        });
        
        if (createError) {
          console.error(`Fehler beim Erstellen des Buckets '${bucketName}': ${createError.message}`);
          return false;
        }
        
        console.log(`Bucket '${bucketName}' erfolgreich erstellt`);
      } else {
        console.log(`Bucket '${bucketName}' existiert bereits`);
      }
      
      return true;
    } catch (error) {
      console.error(`Fehler beim Überprüfen/Erstellen des Buckets:`, error);
      return false;
    }
  } catch (error) {
    console.error(`Unerwarteter Fehler:`, error);
    return false;
  }
};
