// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fewcmtozntpedrsluawj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZld2NtdG96bnRwZWRyc2x1YXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDQ5MzYsImV4cCI6MjA1NzQ4MDkzNn0.4xh1npp9zRyXgXkBGB9auWw3gxOoajDYS8sAIopB-To";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);